#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo 'Illegal number of parameters. Usage: gitCommit "commitComment"  branch (dev, demo or master) all|calls|schema'
else
    if ["$3" -ne "all"]; then
        echo $(date "+%Y-%m-%d %H:%M")>  resources/views/$3/versionTime.blade.php
    else
        echo $(date "+%Y-%m-%d %H:%M")>  resources/views/calls/versionTime.blade.php
        echo $(date "+%Y-%m-%d %H:%M")>  resources/views/schema/versionTime.blade.php
    fi

  echo $(date "+%Y-%m-%d %H:%M")>  resources/views/versionTime.blade.php

  git status
  git add  -A
  git commit -m "$1"
  git push origin "$2"
fi
