#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo 'Illegal number of parameters. Usage: gitCommit "commitComment"  branch (dev, demo or master) all|none|sdCalls|sdSchema'
else
    if [ $3 = all ]; then
      echo $(date "+%Y-%m-%d %H:%M")>  resources/views/versionTime.blade.php
    elif [ $3 != none ]; then
            echo $(date "+%Y-%m-%d %H:%M")>  resources/views/$3/versionTime.blade.php
    fi
  git status
  git add  -A
  git commit -m "$1"
  git push origin "$2"
fi
