#file {{$subDomain}}.conf  Generated by unix.apacheConf.blade {{$generated}}
<Directory /var/www/{{$rootPath}}/public_html>
   # https://httpd.apache.org/docs/2.4/mod/core.html#directory
   
   # Require all granted:  Access is allowed unconditionally.
   Require all granted
   
   # Options= Indexes: If a URL which maps to a directory is requested and there is no DirectoryIndex (e.g., index.html) in that directory, then mod_autoindex will return a formatted listing of the directory.
   # Options= FollowSymLinks: The server will follow symbolic links in this directory. This is the default setting. 
   #Options Indexes FollowSymLinks
   
   ## AllowOverride All: Any directive which has the .htaccess Context is allowed in .htaccess files.
   AllowOverride All
</Directory>
<VirtualHost *:80>
   # https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost
   ServerName {{$subDomain}}
   ServerAlias www.{{$subDomain}}
   ServerAdmin trygve.botnen@gmail.com
   DocumentRoot /var/www/{{$rootPath}}/public_html

   ErrorLog  /var/www/{{$rootPath}}/logs/error.log
   CustomLog /var/www/{{$rootPath}}/logs/access.log combined
	
   RewriteEngine on
   RewriteCond %{SERVER_NAME} ={{$subDomain}} [OR]
   RewriteCond %{SERVER_NAME} =www.{{$subDomain}}
   RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
